apiVersion: v1
kind: PersistentVolume
metadata: 
  name: deathstar-nfs
  labels: 
    pv: deathstar-nfs
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /home1/root/DeathStarBench
    server: 10.0.0.252