apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: deathstar-nfs
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs
  selector:
    matchLabels:
      pv: deathstar-nfs