apiVersion: v1
kind: PersistentVolume
metadata: 
  name: deathstar-jaegerconfig-nfs
  labels: 
    pv: deathstar-jaegerconfig-nfs
spec:
  capacity:
    storage: 1Mi
  accessModes:
  - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /home1/root/DeathStarBench/socialNetwork/nginx-web-server/jaeger-config.json
    server: 10.0.0.252