apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: deathstar-nfs-pvc
  namespace: media-microsvc
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 100Mi
  storageClassName: nfs
  selector:
    matchLabels:
      pv: deathstar-nfs-pv