---
apiVersion: v1
kind: Service
metadata:
  name: user-review-service
  namespace: media-microsvc
  labels:
    death-star-project: media-microsvc
    app-name: user-review-service
spec:
  ports:
  - port: 9090
  selector:
    death-star-project: media-microsvc
    app-name: user-review-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
  name: user-review-service
  namespace: media-microsvc
  labels:
    death-star-project: media-microsvc
    app-name: user-review-service
spec:
  replicas: 1
  selector:
    matchLabels:
      death-star-project: media-microsvc
      app-name: user-review-service
  template:
    metadata:
      labels: 
        death-star-project: media-microsvc
        app-name: user-review-service
        OUTPUT1: user-review-redis
        OUTPUT2: user-review-mongodb
        INPUT: compose-review-service
      name: user-review-service
    spec:
      containers:
      - name: user-review-service
        image: poanpan/media-microservices-local-jaeger:v0.0.1
        command: ["UserReviewService"]
        resources: 
          requests: 
            cpu: "600m"
            memory: "30Mi"
      restartPolicy: Always
      # schedulerName: poseidon
