---
apiVersion: v1
kind: Service
metadata:
  name: user-memcached
  namespace: media-microsvc
  labels:
    death-star-project: media-microsvc
    app-name: user-memcached
spec:
  ports:
  - port: 11211
  selector:
    death-star-project: media-microsvc
    app-name: user-memcached
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
  name: user-memcached
  namespace: media-microsvc
  labels:
    death-star-project: media-microsvc
    app-name: user-memcached
spec:
  replicas: 1
  selector:
    matchLabels:
      death-star-project: media-microsvc
      app-name: user-memcached
  template:
    metadata:
      labels: 
        death-star-project: media-microsvc
        app-name: user-memcached
        INPUT: user-service
      name: user-memcached
    spec:
      containers:
      - name: user-memcached
        image: poanpan/memcached:v1
        resources: 
          requests: 
            cpu: "50m"
            memory: "13Mi"
      restartPolicy: Always
      # schedulerName: poseidon
