apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: deathstar-sn-mf-nfs-pvc
  namespace: social-network
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 1Mi
  storageClassName: nfs
  selector:
    matchLabels:
      pv: deathstar-sn-mf-nfs-pv