apiVersion: v1
kind: PersistentVolume
metadata: 
  name: deathstar-sn-nws-nfs-pv
  labels: 
    pv: deathstar-sn-nws-nfs-pv
spec:
  capacity:
    storage: 1Mi
  accessModes:
  - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /mnt/s2/DeathStarBench_others/socialNetwork/nginx-web-server
    server: 10.0.0.23
