---
apiVersion: v1
kind: Service
metadata:
  name: media-frontend
  labels:
    death-star-project: social-network
    app-name: media-frontend
  namespace: social-network
spec:
  type: NodePort
  ports:
  - port: 8080
    name: tcp
    targetPort: 8080
    nodePort: 31001
  selector:
    death-star-project: social-network
    app-name: media-frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
  name: media-frontend
  labels:
    death-star-project: social-network
    app-name: media-frontend
  namespace: social-network
spec:
  replicas: 1
  selector:
    matchLabels:
      death-star-project: social-network
      app-name: media-frontend
  template:
    metadata:
      annotations:
        io.cilium.proxy-visibility: "<Egress/9090/TCP/HTTP>,<Egress/6379/TCP/REDIS>,<Egress/11211/TCP/MEMCACHED>,<Egress/27107/TCP/MONGODB>,<Egress/5672/TCP/RABBITMQ>,<Ingress/9090/TCP/HTTP>,<Ingress/6379/TCP/REDIS>,<Ingress/11211/TCP/MEMCACHED>,<Ingress/27017/TCP/MONGODB>,<Ingress/5672/TCP/RABBITMQ>"

      labels: 
        death-star-project: social-network
        app-name: media-frontend
      name: media-frontend
    spec:
      containers:
      - name: media-frontend
        image: yg397/media-frontend:xenial
        ports: 
        - containerPort: 8080
        volumeMounts:
        # use pv
        - mountPath: /usr/local/openresty/nginx/lua-scripts
          name: deathstar-sn-mf-nfs-pvc
          subPath: lua-scripts-k8s
        - mountPath: /usr/local/openresty/nginx/conf/nginx.conf
          name: deathstar-sn-mf-nfs-pvc
          subPath: conf/nginx-k8s.conf

        # use host-path
        # - mountPath: /usr/local/openresty/nginx/lua-scripts
        #   name: lua-scripts
        # - mountPath: /usr/local/openresty/nginx/conf/nginx.conf
        #   name: nginx-conf
        resources: 
          requests: 
            cpu: "5m"
            memory: "20Mi"
      restartPolicy: Always
      volumes:
      # use pv
      - name: deathstar-sn-mf-nfs-pvc
        persistentVolumeClaim:
          claimName: deathstar-sn-mf-nfs-pvc
        
      # use host-path
      # - name: lua-scripts
      #   hostPath: 
      #     path: /root/DeathStarBench/socialNetwork/media-frontend/lua-scripts-k8s
      #     type: Directory
      # - name: nginx-conf
      #   hostPath: 
      #     path: /root/DeathStarBench/socialNetwork/media-frontend/conf/nginx-k8s.conf
      #     type: File
      # nodeName: 10.0.0.13
      # schedulerName: poseidon
