---
apiVersion: v1
kind: Service
metadata:
  name: nginx-thrift
  labels:
    death-star-project: social-network
    app-name: nginx-thrift
  namespace: social-network
spec:
  type: NodePort
  ports:
  - port: 8080
    name: http
    targetPort: 8080
    nodePort: 31000
  selector:
    death-star-project: social-network
    app-name: nginx-thrift
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
  name: nginx-thrift
  labels:
    death-star-project: social-network
    app-name: nginx-thrift
  namespace: social-network
spec:
  replicas: 1
  selector:
    matchLabels:
      death-star-project: social-network
      app-name: nginx-thrift
  template:
    metadata:
      annotations:
        io.cilium.proxy-visibility: "<Egress/9090/TCP/HTTP>,<Egress/6379/TCP/REDIS>,<Egress/11211/TCP/MEMCACHED>,<Egress/27107/TCP/MONGODB>,<Egress/5672/TCP/RABBITMQ>,<Ingress/9090/TCP/HTTP>,<Ingress/6379/TCP/REDIS>,<Ingress/11211/TCP/MEMCACHED>,<Ingress/27017/TCP/MONGODB>,<Ingress/5672/TCP/RABBITMQ>"

      labels: 
        death-star-project: social-network
        app-name: nginx-thrift
        OUTPUT1: social-graph-service
        OUTPUT2: text-service
        OUTPUT3: media-service
        OUTPUT4: home-timeline-service
        OUTPUT5: user-service
        OUTPUT6: unique-id-service
        OUTPUT7: user-timeline-service
      name: nginx-thrift
    spec:
      containers:
      - name: nginx-thrift
        image: yg397/openresty-thrift:xenial
        ports: 
        - containerPort: 8080
        
        volumeMounts:
        # use pv
        - mountPath: /usr/local/openresty/nginx/lua-scripts
          name: deathstar-sn-nws-nfs-pvc
          subPath: lua-scripts-k8s
        - mountPath: /usr/local/openresty/nginx/pages
          name: deathstar-sn-nws-nfs-pvc
          subPath: pages
        # TODO: ConfigMap is more suitable for config files. 
        # Maybe we can change config WITHOUT stopping service
        - mountPath: /usr/local/openresty/nginx/conf/nginx.conf
          name: deathstar-sn-nws-nfs-pvc
          subPath: conf/nginx-k8s.conf
        - mountPath: /usr/local/openresty/nginx/jaeger-config.json
          name: deathstar-sn-nws-nfs-pvc
          subPath: jaeger-config.json
        - mountPath: /gen-lua
          name: deathstar-sn-gl-nfs-pvc

        # use host-path
        # - mountPath: /usr/local/openresty/nginx/lua-scripts
        #   name: lua-scripts
        # - mountPath: /usr/local/openresty/nginx/pages
        #   name: pages
        # - mountPath: /usr/local/openresty/nginx/conf/nginx.conf
        #   name: nginx-conf
        # - mountPath: /usr/local/openresty/nginx/jaeger-config.json
        #   name: jaeger-config-json
        # - mountPath: /gen-lua
        #   name: gen-lua
        # resources: 
        #   requests: 
        #     cpu: "10000m"
        #     memory: "200Mi"
      restartPolicy: Always
      volumes:
      # use pv
      - name: deathstar-sn-nws-nfs-pvc
        persistentVolumeClaim:
          claimName: deathstar-sn-nws-nfs-pvc
      - name: deathstar-sn-gl-nfs-pvc
        persistentVolumeClaim:
          claimName: deathstar-sn-gl-nfs-pvc
        
      # use host-path
      # volumes:
      # - name: lua-scripts
      #   hostPath: 
      #     path: /root/DeathStarBench/socialNetwork/nginx-web-server/lua-scripts-k8s
      #     type: Directory
      # - name: pages
      #   hostPath: 
      #     path: /root/DeathStarBench/socialNetwork/nginx-web-server/pages
      #     type: Directory
      # - name: nginx-conf
      #   hostPath: 
      #     path: /root/DeathStarBench/socialNetwork/nginx-web-server/conf/nginx-k8s.conf
      #     type: File
      # - name: jaeger-config-json
      #   hostPath: 
      #     path: /root/DeathStarBench/socialNetwork/nginx-web-server/jaeger-config.json
      #     type: File
      # - name: gen-lua
      #   hostPath: 
      #     path: /root/DeathStarBench/socialNetwork/gen-lua
      #     type: Directory

      # nodeName: 10.0.0.13
      # schedulerName: poseidon
