apiVersion: v1
kind: PersistentVolume
metadata:
  name: reservation-pv
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  storageClassName: reservation-storage
  hostPath:
    path: /home/oslab/eskim/eskim_storage/DeathStarBench_2/hotelReservation/data/volumes/reservation-pv   # Where all the hard drives are mounted
    type: Directory
