apiVersion: v1
kind: PersistentVolume
metadata: 
  name: config-pv
spec:
  volumeMode: Filesystem
  capacity:
    storage: 300Mi
  accessModes:
  - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: config-storage
  nfs:
    path: /mnt/s2/DeathStarBench_2/socialNetwork/config
    server: 10.0.0.23
