apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: home-timeline-redis
  name: home-timeline-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: home-timeline-redis
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: home-timeline-redis
    spec:
      containers:
        - image: redis
          name: home-timeline-redis
          resources: {}
      hostname: home-timeline-redis
      restartPolicy: Always
status: {}
