apiVersion: v1
kind: PersistentVolume
metadata: 
  name: jaeger-pv
spec:
  volumeMode: Filesystem
  capacity:
    storage: 100Mi
  accessModes:
  - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: jaeger-storage
  nfs:
    path: /mnt/s2/DeathStarBench_2/socialNetwork/nginx-web-server
    server: 10.0.0.23
