apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: nginx-thrift
  name: nginx-thrift
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nginx-thrift
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: nginx-thrift
    spec:
      containers:
        - image: yg397/openresty-thrift:xenial
          name: nginx-thrift
          ports:
            - containerPort: 8080
          resources: {}
          volumeMounts:
            - mountPath: /usr/local/openresty/nginx/lua-scripts
              name: thrift-pvc
              subPath: lua-scripts
            - mountPath: /usr/local/openresty/nginx/pages
              name: thrift-pvc
              subPath: pages
            - mountPath: /usr/local/openresty/nginx/conf/nginx.conf
              name: thrift-pvc
              subPath: conf/nginx.conf
            - mountPath: /usr/local/openresty/nginx/jaeger-config.json
              name: thrift-pvc
              subPath: jaeger-config.json
            - mountPath: /gen-lua
              name: genlua-pvc
      hostname: nginx-thrift
      restartPolicy: Always
      volumes:
        - name: thrift-pvc
          persistentVolumeClaim:
            claimName: thrift-pvc
        - name: genlua-pvc
          persistentVolumeClaim:
            claimName: genlua-pvc
status: {}
