apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: text-service
  name: text-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: text-service
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: text-service
    spec:
      containers:
        - command:
            - TextService
          image: yg397/social-network-microservices:latest
          name: text-service
          resources: {}
          volumeMounts:
            - mountPath: /social-network-microservices/config
              name: config-pvc
      hostname: text-service
      restartPolicy: Always
      volumes:
        - name: config-pvc
          persistentVolumeClaim:
            claimName: config-pvc
status: {}
